[template]
src = "blacklist.txt.tmpl"
dest = "/usr/local/etc/haproxy/blacklist.txt"
keys = [
    "/blacklist"
]
reload_cmd = "cat /usr/local/etc/haproxy/blacklist.txt && haproxy -f /usr/local/etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -x /var/run/haproxy.sock -sf $(cat /var/run/haproxy.pid) -D"